version: "3.8"

services:
  client:
    env_file:
      - .env
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: pr-tracker-client
    command: yarn dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/
    networks:
      - pr-tracker-client_network

networks:
  pr-tracker-client_network:
    driver: bridge
